<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTaxbV9w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTaxbV9w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTaxbV9w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTaxbV9w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTaxbV9w\App_KernelDevDebugContainer([
    'container.build_hash' => 'TaxbV9w',
    'container.build_id' => '411de2cd',
    'container.build_time' => 1674517207,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTaxbV9w');
