<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB53Jtob\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB53Jtob/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB53Jtob.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB53Jtob\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB53Jtob\App_KernelDevDebugContainer([
    'container.build_hash' => 'B53Jtob',
    'container.build_id' => '5966e682',
    'container.build_time' => 1674741375,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB53Jtob');
