<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKddn2Su\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKddn2Su/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKddn2Su.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKddn2Su\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKddn2Su\App_KernelDevDebugContainer([
    'container.build_hash' => 'Kddn2Su',
    'container.build_id' => '664c6f97',
    'container.build_time' => 1674566769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKddn2Su');
