<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY4miXK6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY4miXK6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY4miXK6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY4miXK6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY4miXK6\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y4miXK6',
    'container.build_id' => 'cb0a23aa',
    'container.build_time' => 1674668056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY4miXK6');
