<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjBcDKS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjBcDKS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXjBcDKS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXjBcDKS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXjBcDKS\App_KernelDevDebugContainer([
    'container.build_hash' => 'XjBcDKS',
    'container.build_id' => '87fcce8d',
    'container.build_time' => 1674657277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjBcDKS');
