<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQHOEeMF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQHOEeMF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQHOEeMF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQHOEeMF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQHOEeMF\App_KernelDevDebugContainer([
    'container.build_hash' => 'QHOEeMF',
    'container.build_id' => '341a17ef',
    'container.build_time' => 1674738808,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQHOEeMF');
