<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6I8OBmT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6I8OBmT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6I8OBmT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6I8OBmT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6I8OBmT\App_KernelDevDebugContainer([
    'container.build_hash' => '6I8OBmT',
    'container.build_id' => '47ec4e6a',
    'container.build_time' => 1674691297,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6I8OBmT');
