<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDuOhxgb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDuOhxgb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDuOhxgb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDuOhxgb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDuOhxgb\App_KernelDevDebugContainer([
    'container.build_hash' => 'DuOhxgb',
    'container.build_id' => 'bc8361ea',
    'container.build_time' => 1674581479,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDuOhxgb');
